api/urls.py
from django.urls import path

from . import views

app_name = 'api'
urlpatterns = [
    path('subjects', views.subjects_list, name='subjects'),
]

app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('query/', views.query, name='query'),
    path('all/', views.show_all, name='all'),
]

test_task/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('', RedirectView.as_view(url='/app/')),
    path('api/', include('api.urls')),
]

api/models.py
from django.db import models

# Create your models here.

app/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.
class Subject(models.Model):
    inn = models.CharField(max_length=10, primary_key=True)
    ogrn = models.CharField(max_length=13)
    request_time = models.DateTimeField(auto_now_add=True)
    registration_date = models.CharField(max_length=50)
    name_ex = models.TextField()

    def requested_recently(self):
        return self.request_time >= timezone.now() - datetime.timedelta(minutes=5)

    def to_dict(self):
        return Subject.objects.filter(pk=self.pk).values().first()

    def __str__(self):
        return self.name_ex


class Query(models.Model):
    query_string = models.CharField(max_length=13, primary_key=True)
    result = models.ForeignKey(Subject, on_delete=models.CASCADE)

    def __str__(self):
        return self.result.name_ex

api/views.py
from django.http import JsonResponse
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt

from api.serializers import SubjectSerializer
from app.models import Subject
from app.utils import fetch_data, get_subject_by_query_string


# Create your views here.
@csrf_exempt
def subjects_list(request):
    if request.method == 'GET':
        subjects= Subject.objects.all()
        serializer = SubjectSerializer(subjects, many=True)
        return JsonResponse(serializer.data, safe=False)

    elif request.method == 'POST':
        query_string = request.POST.get('query', '')
        subject = get_subject_by_query_string(query_string=query_string)

        if subject and subject.requested_recently():
            subject.request_time = timezone.now()
            subject.save(update_fields=['request_time'])
            serializer = SubjectSerializer(data=subject.to_dict())
            if serializer.is_valid():
                return JsonResponse(serializer.data, status=201)
        else:
            data = fetch_data(
                url='https://rmsp.nalog.ru/search-proc.json',
                query_string=query_string,
            )
            if data:
                subject = Subject(**data)
                subject.save()
                subject.query_set.create(query_string=query_string)
                serializer = SubjectSerializer(data=subject.to_dict())
                if serializer.is_valid():
                    return JsonResponse(serializer.data, status=201)

        return JsonResponse({'error': 'Query string is invalid'}, status=400)

app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse
from django.utils import timezone

from app.models import Subject
from app.utils import fetch_data, get_subject_by_query_string


# Create your views here.
def index(request):
    try:
        subject = Subject.objects.all().order_by('-request_time')[0]
    except IndexError:
        subject = None

    return render(request=request,
                  template_name='app/index.html',
                  context={'subject': subject})


def show_all(request):
    try:
        subjects_list = Subject.objects.all().order_by('-request_time')
    except IndexError:
        subjects_list = None

    return render(request=request,
                  template_name='app/all.html',
                  context={'subjects_list': subjects_list})


def query(request):
    query_string = request.POST.get('query', '')
    subject = get_subject_by_query_string(query_string=query_string)

    if subject and subject.requested_recently():
        subject.request_time = timezone.now()
        subject.save(update_fields=['request_time'])
    else:
        data = fetch_data(
            url='https://rmsp.nalog.ru/search-proc.json',
            query_string=query_string,
        )
        if data:
            subject = Subject(**data)
            subject.save()
            subject.query_set.create(query_string=query_string)

    return HttpResponseRedirect(reverse('app:index'))

templates/app/all.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All queries</title>
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/menu.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/content.css' %}">
</head>
<body>
    {% include 'app/menu.html' %}
    {% if subjects_list %}
        <div class="content-wrapper">
            {% for subject in subjects_list %}
                <div class="content-holder">
                    <div class="name-holder">
                        <h3>{{ subject.name_ex }}</h3>
                    </div>

                    <div class="data-holder">
                        <p>INN: {{ subject.inn }}</p>
                        <p>OGRN: {{ subject.ogrn }}</p>
                        <p>REGISTRATION DATE: {{ subject.registration_date }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
</body>
</html>

templates/app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>App</title>
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/search-form.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/menu.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/content.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/button.css' %}">

</head>
<body>
    {% include 'app/menu.html' %}
    <div class="form-wrapper">
        <form method="post" action="{% url 'app:query' %}">
            {% csrf_token %}
            <p id="query-type">Unknown</p>
            <input class="input-area" id="query" type="text" name="query" maxlength="100" placeholder="ОГРН/ИНН" required><br>
            <input id="submit-btn" class="button" type="submit" disabled>
        </form>
    </div>

    {% if subject %}
    <div class="content-wrapper">
        <div class="content-holder">
            <div class="name-holder">
                <h3>{{ subject.name_ex }}</h3>
            </div>

            <div class="data-holder">
                <p>INN: {{ subject.inn }}</p>
                <p>OGRN: {{ subject.ogrn }}</p>
                <p>REGISTRATION DATE: {{ subject.registration_date }}</p>
            </div>
        </div>
    </div>
    {% endif %}

    <script src="{% static 'app/js/index.js' %}"></script>
</body>
</html>

templates/app/menu.html
{% load static %}
<div class="menu-wrapper">
    <ul>
        <li><a href="{% url 'app:index' %}">Search</a></li>
        <li><a href="{% url 'app:all' %}">All</a></li>
    </ul>
</div>